name: Maintenance

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Remove expired servers
      uses: ./.github/workflows/actions/maintenance
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4